'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({...(process.env.NAGWEB_BROWSER?{executablePath:process.env.NAGWEB_BROWSER}:{}),headless:true,args:['--enable-unsafe-swiftshader']});
 try{
  fs.mkdirSync('work',{recursive:true});const vendor=process.env.NAGWEB_TEST_VENDOR_DIR;
  const source=f=>fs.readFileSync(vendor?path.join(vendor,f):require.resolve({'three.cjs':'three/build/three.js','GLTFLoader.js':'three/examples/js/loaders/GLTFLoader.js','gsap.js':'gsap/dist/gsap.js','ScrollTrigger.js':'gsap/dist/ScrollTrigger.js'}[f]));
  const page=await browser.newPage({viewport:{width:1000,height:800}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('https://**/*',r=>{const u=r.request().url(),f=/three(?:\.min)?\.js/.test(u)?'three.cjs':/GLTFLoader/.test(u)?'GLTFLoader.js':/ScrollTrigger/.test(u)?'ScrollTrigger.js':/gsap.min/.test(u)?'gsap.js':null;return f?r.fulfill({contentType:'text/javascript',body:source(f)}):r.abort();});
  await page.goto('file:///'+path.resolve('index.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.NAGWEB_CREATE_SPATIAL_RENDERER);
  const generated=await page.evaluate(()=>{
   const p=starterProject();snapOn=false;p.progress=false;p.bloom=false;p.light='soft';
   p.sections=[mkSection({id:'space',layout:'free',sdEnabled:true,sdCameraEnabled:true,sdEase:'linear',sdCameraFrames:[{at:0,x:0,y:0,z:0},{at:100,x:60,y:20,z:20,rotate:5,rotateX:8,rotateY:16}],elements:[
    mkEl('shape3d',{id:'box',shape:'box',motion:'still',env:'',x:65,y:50,w:20,offZ:1,dragRotate:true,dragInertia:0}),
    mkEl('shape3d',{id:'model',shape:'model',modelId:'triangle',motion:'still',env:'',x:35,y:50,w:20,dragRotate:true,dragAxis:'y',dragInertia:0}),
    mkEl('shape3d',{id:'far',shape:'box',motion:'still',env:'',x:65,y:50,w:20,offZ:-2,dragRotate:true,dragInertia:0})]})];
   const bin=new Float32Array([-1,-1,0,1,-1,0,0,1,0]),json={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{mesh:0}],meshes:[{name:'realGLB',primitives:[{attributes:{POSITION:0}}]}],buffers:[{byteLength:bin.byteLength}],bufferViews:[{buffer:0,byteOffset:0,byteLength:bin.byteLength}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[-1,-1,0],max:[1,1,0]}]};
   let j=JSON.stringify(json);while(j.length%4)j+=' ';const bytes=new Uint8Array(28+j.length+bin.byteLength),v=new DataView(bytes.buffer);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,bytes.length,true);v.setUint32(12,j.length,true);v.setUint32(16,0x4e4f534a,true);bytes.set(new TextEncoder().encode(j),20);v.setUint32(20+j.length,bin.byteLength,true);v.setUint32(24+j.length,0x004e4942,true);bytes.set(new Uint8Array(bin.buffer),28+j.length);
   p.assets.models=[{id:'triangle',format:'glb',data:btoa(String.fromCharCode(...bytes))}];return{edit:generateSite(structuredClone(p),true,false,false),exported:generateSite(structuredClone(p),false,false,false)};
  });
  async function open(mode){
   errors.length=0;await page.emulateMedia({reducedMotion:'reduce'});
   const audit='<script>window.__spinListeners=new Set();window.__changes=[];window.addEventListener("message",function(e){if(e.data&&e.data.sc)window.__changes.push(e.data);});["addEventListener","removeEventListener"].forEach(function(m){var original=window[m];window[m]=function(t,f,o){if(f&&/^(spinDown|spinMove|endDrag|blurSpin|hideSpin)$/.test(f.name))window.__spinListeners[m==="addEventListener"?"add":"delete"](t+":"+f.name);return original.call(this,t,f,o);};});<\/script>';
   const html=generated[mode].replace('<head>','<head>'+audit).replace('  function connectSpatial3D(ev){','  window.__pickTest={adapter:spatial3D,objects:objects,renderer:renderer,camera:camera,tick:tick,get pick(){return typeof pickDraggable==="function"?pickDraggable:null;}};\n  function connectSpatial3D(ev){');
   const f='work/interaction-'+mode+'.html';fs.writeFileSync(f,html);await page.goto('file:///'+path.resolve(f).replaceAll('\\','/'));await page.waitForFunction(()=>window.__pickTest&&window.__NAG_SCROLL_DIRECTOR&&window.__pickTest.objects[1].children.some(n=>n.children.some(m=>m.name==='realGLB')));
   await page.emulateMedia({reducedMotion:'no-preference'});
   await page.evaluate(()=>{const d=window.__pickTest;window.__NAG_SCROLL_DIRECTOR.space.set(.5);d.tick();window.__pickScreen=i=>{d.tick();const g=d.objects[i],v=d.adapter.view(g),p=new THREE.Box3().setFromObject(g).getCenter(new THREE.Vector3()).project(v.camera);return{x:v.rect.left+(p.x+1)*v.rect.width/2,y:v.rect.top+(1-p.y)*v.rect.height/2};};window.__pickState=()=>({rot:d.objects.map(g=>[g.rotation.x,g.rotation.y]),pos:d.objects.map(g=>g.userData.holder.position.toArray()),progress:window.__NAG_SCROLL_DIRECTOR.space.progress()});});
  }
  const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,a+' != '+b);
  await open('exported');
  for(const [i,dx,dy] of [[0,40,24],[1,30,20]]){
   const start=await page.evaluate(i=>({point:window.__pickScreen(i),state:window.__pickState()}),i);
   assert.equal(await page.evaluate(p=>window.__pickTest.pick(p.x,p.y).userData.o.id,start.point),i?'model':'box');
   await page.mouse.move(start.point.x,start.point.y);await page.mouse.down();await page.mouse.move(start.point.x+dx,start.point.y+dy,{steps:5});await page.mouse.up();
   const end=await page.evaluate(()=>window.__pickState());close(end.rot[i][1]-start.state.rot[i][1],dx*.008);close(end.rot[i][0]-start.state.rot[i][0],i?0:dy*.008);assert.deepEqual(end.pos,start.state.pos);assert.equal(end.progress,.5);assert.deepEqual(end.rot[2],start.state.rot[2]);
  }
  console.log('PASS exported: real mouse rotates the visible box and loaded GLB under a moving/rotated camera; axis and Director progress preserved');
  const right=await page.evaluate(()=>({point:window.__pickScreen(0),state:window.__pickState()}));
  await page.mouse.move(right.point.x,right.point.y);await page.mouse.down({button:'right'});await page.mouse.move(right.point.x+20,right.point.y+20);await page.mouse.up({button:'right'});assert.deepEqual((await page.evaluate(()=>window.__pickState())).rot,right.state.rot);
  await page.evaluate(p=>{const b=document.createElement('button');b.id='pick-control';b.textContent='Control';b.style.cssText='position:fixed;z-index:999;left:'+(p.x-30)+'px;top:'+(p.y-20)+'px;width:60px;height:40px';document.body.appendChild(b);},right.point);
  await page.mouse.move(right.point.x,right.point.y);await page.mouse.down();await page.mouse.move(right.point.x+10,right.point.y+10);await page.mouse.up();assert.deepEqual((await page.evaluate(()=>window.__pickState())).rot,right.state.rot);await page.evaluate(()=>document.querySelector('#pick-control').remove());
  const clipped=await page.evaluate(()=>{const d=window.__pickTest,s=d.objects[0].userData.anchorEl.parentElement;s.style.cssText+=';position:fixed;top:0;left:0;width:500px;height:400px;min-height:400px';d.objects[0].userData.anchorEl.style.left='98%';d.objects[1].visible=false;d.objects[2].visible=false;window.__NAG_SCROLL_DIRECTOR.space.set(0);d.tick();return{pick:d.pick(510,200),state:window.__pickState()};});assert.equal(clipped.pick,null);
  await page.mouse.move(510,200);await page.mouse.down();await page.mouse.move(550,224);await page.mouse.up();assert.deepEqual((await page.evaluate(()=>window.__pickState())).rot,clipped.state.rot);
  assert.equal(await page.evaluate(()=>window.__pickTest.pick(480,200).userData.o.id),'box');await page.mouse.move(480,200);await page.mouse.down();await page.mouse.move(500,210);await page.mouse.up();close((await page.evaluate(()=>window.__pickState())).rot[0][1]-clipped.state.rot[0][1],.16);
  console.log('PASS exported: stage scissor rejects a hidden portion, visible edge remains draggable, right click and buttons do not rotate objects');
  await page.evaluate(()=>{const d=window.__pickTest,s=d.objects[0].userData.anchorEl.parentElement;s.style.cssText='';d.objects[0].userData.anchorEl.style.left='65%';d.objects[1].visible=true;d.objects[2].visible=true;d.tick();});
  await page.setViewportSize({width:500,height:600});await page.waitForFunction(()=>Math.abs(window.__pickTest.adapter.view(window.__pickTest.objects[0]).camera.aspect-5/6)<1e-8);
  await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>window.__pickTest.adapter.view(window.__pickTest.objects[0]).camera.position.x===0);assert.equal(await page.evaluate(()=>{const p=window.__pickScreen(0);return window.__pickTest.pick(p.x,p.y).userData.o.id;}),'box');
  const cancelled=await page.evaluate(()=>{const d=window.__pickTest,p=window.__pickScreen(0),g=d.objects[0];g.userData.o.dragInertia=.8;const before=g.rotation.y;
   const send=(type,id,x)=>window.dispatchEvent(new PointerEvent(type,{pointerId:id,pointerType:'touch',button:0,clientX:x,clientY:p.y}));
   send('pointerdown',7,p.x);send('pointermove',8,p.x+100);send('pointerup',8,p.x+100);const foreign=g.rotation.y;send('pointermove',7,p.x+12);const active=g.rotation.y;send('pointercancel',7,p.x+12);d.tick();const ended=g.rotation.y;send('pointermove',7,p.x+80);d.tick();return{before,foreign,active,ended,after:g.rotation.y,vx:g.userData.spinVX,vy:g.userData.spinVY};});
  close(cancelled.before,cancelled.foreign);close(cancelled.active-cancelled.before,.096);close(cancelled.active,cancelled.ended);close(cancelled.after,cancelled.ended);assert.equal(cancelled.vx,0);assert.equal(cancelled.vy,0);
  const lifecycle=await page.evaluate(()=>{const d=window.__pickTest,p=window.__pickScreen(0),g=d.objects[0];window.dispatchEvent(new PointerEvent('pointerdown',{pointerId:9,button:0,clientX:p.x,clientY:p.y}));window.dispatchEvent(new PointerEvent('pointermove',{pointerId:9,clientX:p.x+20,clientY:p.y}));window.dispatchEvent(new Event('blur'));const before=g.rotation.y;d.tick();const after=g.rotation.y;const registered=window.__spinListeners.size;window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));return{before,after,vx:g.userData.spinVX,vy:g.userData.spinVY,registered,retained:window.__spinListeners.size};});close(lifecycle.before,lifecycle.after);assert.equal(lifecycle.vx,0);assert.equal(lifecycle.vy,0);assert.equal(lifecycle.registered,6);assert.equal(lifecycle.retained,6);
  const resumed=await page.evaluate(()=>({point:window.__pickScreen(0),rotation:window.__pickTest.objects[0].rotation.y}));await page.mouse.move(resumed.point.x,resumed.point.y);await page.mouse.down();await page.mouse.move(resumed.point.x+10,resumed.point.y);await page.mouse.up();assert.ok((await page.evaluate(()=>window.__pickTest.objects[0].rotation.y))>resumed.rotation);
  await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));assert.equal(await page.evaluate(()=>window.__spinListeners.size),0);assert.deepEqual(errors,[]);
  console.log('PASS exported: resize/reduced motion, pointer ownership, cancel/blur, bfcache retention and final listener cleanup');

  await page.setViewportSize({width:1000,height:800});await open('edit');
  await page.evaluate(()=>{window.__pickTest.objects[2].userData.anchorEl.style.display='none';window.__pickTest.tick();});
  for(const i of [0,1]){
   const alignment=await page.evaluate(i=>{const d=window.__pickTest,g=d.objects[i],p=window.__pickScreen(i),r=document.querySelector('.sc-proxy[data-id="'+g.userData.o.id+'"]').getBoundingClientRect();return{hidden:g.userData.anchorEl.style.visibility,inside:p.x>=r.left&&p.x<=r.right&&p.y>=r.top&&p.y<=r.bottom};},i);assert.equal(alignment.hidden,'hidden');assert.equal(alignment.inside,true,'editor proxy contains the visible object after camera motion');
   const gesture=await page.evaluate(i=>{const d=window.__pickTest,g=d.objects[i],v=d.adapter.view(g),node=g.userData.anchorEl,proxy=document.querySelector('.sc-proxy[data-id="'+g.userData.o.id+'"]'),r=proxy.getBoundingClientRect(),sx=r.left+r.width/2,sy=r.top+r.height/2,ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((sx-v.rect.left)/v.rect.width*2-1,1-(sy-v.rect.top)/v.rect.height*2),v.camera);const z=g.userData.holder.position.z,p=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,0,1),-z),new THREE.Vector3());p.add(new THREE.Vector3(50,-35,0));p.project(v.camera);return{id:g.userData.o.id,start:{x:sx,y:sy},end:{x:v.rect.left+(p.x+1)*v.rect.width/2,y:v.rect.top+(1-p.y)*v.rect.height/2},expected:{x:+node.dataset.x+50/node.parentElement.clientWidth*100,y:+node.dataset.y+35/node.parentElement.clientHeight*100},before:g.userData.holder.position.toArray(),progress:window.__NAG_SCROLL_DIRECTOR.space.progress()};},i);
   await page.mouse.move(gesture.start.x,gesture.start.y);await page.mouse.down();await page.mouse.move(gesture.end.x,gesture.end.y,{steps:5});await page.mouse.up();
   await page.waitForFunction(id=>window.__changes.some(m=>m.type==='change'&&m.id===id),gesture.id);
   const moved=await page.evaluate(i=>{const d=window.__pickTest;d.tick();return{change:window.__changes.filter(m=>m.type==='change'&&m.id===d.objects[i].userData.o.id).at(-1),position:d.objects[i].userData.holder.position.toArray(),selected:window.__changes.some(m=>m.type==='select'&&m.id===d.objects[i].userData.o.id),progress:window.__NAG_SCROLL_DIRECTOR.space.progress()};},i);
   close(moved.change.x,gesture.expected.x);close(moved.change.y,gesture.expected.y);close(moved.position[0]-gesture.before[0],50);close(moved.position[1]-gesture.before[1],-35);assert.equal(moved.progress,gesture.progress);assert.equal(moved.selected,true);
  }
  await open('edit');
  const size=await page.evaluate(()=>{const d=window.__pickTest,g=d.objects[1],v=d.adapter.view(g);window.dispatchEvent(new MessageEvent('message',{data:{sc:true,type:'selectionset',ids:['model']}}));const handle=document.querySelector('.sc-proxy[data-id="model"] .sc-h.br'),r=handle.getBoundingClientRect(),sx=r.left+r.width/2,sy=r.top+r.height/2,ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((sx-v.rect.left)/v.rect.width*2-1,1-(sy-v.rect.top)/v.rect.height*2),v.camera);const p=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,0,1),-g.userData.holder.position.z),new THREE.Vector3()).add(new THREE.Vector3(50,0,0)).project(v.camera);return{start:{x:sx,y:sy},end:{x:v.rect.left+(p.x+1)*v.rect.width/2,y:v.rect.top+(1-p.y)*v.rect.height/2},scale:g.userData.holder.scale.x,width:+g.userData.anchorEl.dataset.w,delta:100/g.userData.anchorEl.parentElement.clientWidth*100};});
  await page.mouse.move(size.start.x,size.start.y);await page.mouse.down();await page.mouse.move(size.end.x,size.end.y,{steps:5});await page.mouse.up();await page.waitForFunction(()=>window.__changes.some(m=>m.type==='change'&&m.id==='model'));
  const sized=await page.evaluate(()=>{const d=window.__pickTest;d.tick();return{change:window.__changes.filter(m=>m.type==='change'&&m.id==='model').at(-1),scale:d.objects[1].userData.holder.scale.x,progress:window.__NAG_SCROLL_DIRECTOR.space.progress()};});close(sized.change.w,size.width+size.delta);close(sized.scale/size.scale,(size.width+size.delta)/size.width);assert.equal(sized.progress,.5);
  console.log('PASS edit: resize uses the same inverse camera projection and persists the expected width');
  const contextPoint=await page.evaluate(()=>window.__pickScreen(1));await page.mouse.click(contextPoint.x,contextPoint.y,{button:'right'});await page.waitForFunction(()=>window.__changes.some(m=>m.type==='ctx'&&m.id==='model'));
  const editorCancel=await page.evaluate(()=>{const d=window.__pickTest,g=d.objects[0],proxy=document.querySelector('.sc-proxy[data-id="box"]'),r=proxy.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;
   proxy.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:88,button:0,clientX:x,clientY:y}));const before=g.userData.anchorEl.style.left;window.dispatchEvent(new PointerEvent('pointermove',{pointerId:99,clientX:x+100,clientY:y}));const foreign=g.userData.anchorEl.style.left;window.dispatchEvent(new PointerEvent('pointermove',{pointerId:88,clientX:x+20,clientY:y}));const changed=g.userData.anchorEl.style.left;window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:88}));window.dispatchEvent(new PointerEvent('pointermove',{pointerId:88,clientX:x+100,clientY:y}));d.tick();return{before,foreign,changed,after:g.userData.anchorEl.style.left};});assert.equal(editorCancel.foreign,editorCancel.before);assert.notEqual(editorCancel.changed,editorCancel.before);assert.equal(editorCancel.after,editorCancel.changed);
  await page.screenshot({path:'work/interaction-edit.png'});
  const proxyClip=await page.evaluate(()=>{const d=window.__pickTest,g=d.objects[0],s=g.userData.anchorEl.parentElement;s.style.cssText+=';position:fixed;top:0;left:0;width:500px;height:400px;min-height:400px';g.userData.anchorEl.style.left='98%';window.__NAG_SCROLL_DIRECTOR.space.set(0);d.tick();const proxy=document.querySelector('.sc-proxy[data-id="box"]'),r=proxy.getBoundingClientRect();return{right:r.right,top:r.top,bottom:r.bottom,visible:proxy.style.display};});assert.equal(proxyClip.visible,'block');assert.ok(proxyClip.right<=500+1e-5&&proxyClip.top>=0&&proxyClip.bottom<=400+1e-5);
  const releasedProxy=await page.evaluate(()=>{const d=window.__pickTest;d.adapter.destroy();d.tick();return{anchor:d.objects[0].userData.anchorEl.style.visibility,proxy:document.querySelector('.sc-proxy[data-id="box"]').style.display};});assert.equal(releasedProxy.anchor,'');assert.equal(releasedProxy.proxy,'none');
  console.log('PASS edit: projected frame clipping, pointer cancellation and original anchor restoration after detach');assert.deepEqual(errors,[]);console.log('PASS edit: actual mouse selection and saved anchor percentages for box/GLB follow their world plane under a rotated camera');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
